name: automate-newsletter-project-deploy
on:
  push:
    branches:
      - deploy_changes
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    
    - name: Create a python dist
      run:
        python ./setup.py sdist
        
    - name: Copy required scripts
      run: |
              echo "${{ secrets.KEY }}" > secret.pem
              chmod 400 secret.pem
              scp -o StrictHostKeyChecking=no -i secret.pem dist/*.tar.gz ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/home/ubuntu
              scp -o StrictHostKeyChecking=no -i secret.pem deploy_app.sh ${{ secrets.USERNAME }}@${{ secrets.HOST }}:/home/ubuntu

    - name: Run Deploy script
      run: 
              ssh -o StrictHostKeyChecking=no -i secret.pem {{ secrets.USERNAME }}@${{ secrets.HOST }} bash /home/ubuntu/deploy_app.sh


