name: run-github-stats-checkpoint

on:
  workflow_dispatch:
  # schedule:
  #   # Daily at 11:00 IST
  #   #- cron: "30 5 * * *"
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
  push:
    branches:
      - master
    paths:
      - 'tests/data_validation/great_expectations/**'  

jobs:
  great_expectations_validation:
    runs-on: ubuntu-latest
    steps:
      - name: Install python
        uses: actions/setup-python@v3

      - name: Copy Repository contents
        uses: actions/checkout@main

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install great_expectations

      - name: Run Checkpoint
        run: |
          python tests/data_validation/great_expectations/utils/run_ge_tests_11am_checkpoint.py
